version: '3.2'

services:
  console:
    container_name: console
    image: yiisoftware/yii2-php:7.2-apache
    environment:
      - PHP_ENABLE_XDEBUG=1
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
    ports:
    - "8081:80"
    - "9000:9000"