<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Driver licence (both sides in one file)' => 'Licencia de conducir (ambos lados en un archivo)',
    'ID card (both sides in one file)' => 'Tarjeta de identificación (ambos lados en un archivo)',
    'Official company registration document (Kbis extract or equivalent)' => 'Documento oficial de registro de la empresa (extracto de Kbis o equivalente)',
    'Others' => 'Otros',
    'Passport (European Union)' => 'Pasaporte (Unión Europea)',
    'Passport (outside the European Union)' => 'Pasaporte (fuera de la Unión Europea)',
    'Proof of address' => 'Comprobante de domicilio',
    'Residence permit (both sides in one file)' => 'Permiso de residencia (ambos lados en un archivo)',
    'SDD mandate' => 'Mandato SDD',
    'Scan of a proof of IBAN' => 'Escaneo de una prueba de IBAN',
    'Selfie' => 'Selfie',
    'Status' => 'Estado',
];
